POST http://localhost:3000/api/admin/v1/words
{
	"english_spelling": "hello",
	"inglix_spelling": "helO"
}
# HTTP 201

POST http://localhost:3000/api/admin/v1/words
{
	"english_spelling": "okay",
	"inglix_spelling": "OkeE"
}
# HTTP 201

POST http://localhost:3000/api/admin/v1/words
{
	"english_spelling": "tall",
	"inglix_spelling": "tol"
}
# HTTP 201

POST http://localhost:3000/api/admin/v1/words
{
	"english_spelling": "yellow",
	"inglix_spelling": "yelO"
}
# HTTP 201
